import { InMemoryDbService } from "angular-in-memory-web-api";

import { Category } from "./pages/categories/shared/category.model";
import { Entry } from "./pages/entries/shared/entry.model";

export class InMemoryDatabase implements InMemoryDbService {
  createDb() {
    const categories: Category[] = [
      { id: 1, name: "Moradia", description: "Pagamentos de Contas da Casa" },
      { id: 2, name: "Saúde", description: "Plano de Saúde e Remédios" },
      { id: 3, name: "Lazer", description: "Cinema, parques, praia, etc" },
      { id: 4, name: "Salário", description: "Recebimento de Salário" },
      { id: 5, name: "Freelas", description: "Trabalhos como freelancer" },
      { id: 6, name: "Lucro", description: "Dividendos, aluguel..." },
    ];

    const entries: Entry[] = [
      {
        id: 1,
        name: "Gás de Cozinha",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "01/11/2022",
        amount: "70.80",
        type: "expense",
        description: "Qualquer descrição para essa despesa",
      } as Entry,
      {
        id: 2,
        name: "Suplementos",
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: "05/11/2022",
        amount: "15.20",
        type: "expense",
      } as Entry,
      {
        id: 3,
        name: "Salário",
        categoryId: categories[4].id,
        category: categories[4],
        paid: true,
        date: "15/11/2022",
        amount: "1000",
        type: "revenue",
        description: "Lorem ipsum dolor sit amet...",
      } as Entry,
      {
        id: 4,
        name: "Dividendos",
        categoryId: categories[5].id,
        category: categories[5],
        paid: true,
        date: "25/11/2022",
        amount: "350",
        type: "revenue",
      } as Entry,
      {
        id: 5,
        name: "Gás de Cozinha",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "01/12/2022",
        amount: "70.80",
        type: "expense",
        description: "Qualquer descrição para essa despesa",
      } as Entry,
      {
        id: 6,
        name: "Aluguel",
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: "05/12/2022",
        amount: "1500",
        type: "expense",
      } as Entry,
      {
        id: 7,
        name: "Salário",
        categoryId: categories[4].id,
        category: categories[4],
        paid: true,
        date: "15/12/2022",
        amount: "100",
        type: "revenue",
        description: "Lorem ipsum dolor sit amet...",
      } as Entry,
      {
        id: 8,
        name: "Dividendos",
        categoryId: categories[5].id,
        category: categories[5],
        paid: true,
        date: "25/12/2022",
        amount: "350",
        type: "revenue",
      } as Entry,
      {
        id: 9,
        name: "Conta de luz",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "01/01/2023",
        amount: "70.80",
        type: "expense",
        description: "Qualquer descrição para essa despesa",
      } as Entry,
      {
        id: 10,
        name: "Vitaminas",
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: "05/01/2023",
        amount: "15.20",
        type: "expense",
      } as Entry,
      {
        id: 11,
        name: "Salário",
        categoryId: categories[4].id,
        category: categories[4],
        paid: false,
        date: "15/01/2023",
        amount: "1300",
        type: "revenue",
        description: "Lorem ipsum dolor sit amet...",
      } as Entry,
      {
        id: 12,
        name: "Dividendos",
        categoryId: categories[5].id,
        category: categories[5],
        paid: false,
        date: "25/01/2023",
        amount: "100",
        type: "revenue",
      } as Entry,
    ];

    return { categories, entries };
  }
}
