import { InMemoryDbService } from "angular-in-memory-web-api";

import { Category } from "./pages/categories/shared/category.model";
import { Entry } from "./pages/entries/shared/entry.model";

export class InMemoryDatabase implements InMemoryDbService {
  createDb() {
    const categories: Category[] = [
      { id: 1, name: "Home", description: "House bill payments" },
      { id: 2, name: "Health", description: "Health plan and medicine" },
      { id: 3, name: "Recreation", description: "Cinema, parks, beach, etc" },
      { id: 4, name: "Salary", description: "Salary receipt" },
      { id: 5, name: "Freelance", description: "Freelance jobs" },
      { id: 6, name: "Profit", description: "Dividends, rent" },
    ];

    const entries: Entry[] = [
      {
        id: 1,
        name: "Cooking gas",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "01/03/2023",
        amount: "70.80",
        type: "expense",
        description: "Description lorem ipsum",
      } as Entry,
      {
        id: 2,
        name: "Vitamins",
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: "05/03/2023",
        amount: "15.20",
        type: "expense",
      } as Entry,
      {
        id: 3,
        name: "Salary",
        categoryId: categories[4].id,
        category: categories[4],
        paid: true,
        date: "15/03/2023",
        amount: "1000",
        type: "revenue",
        description: "Description lorem ipsum",
      } as Entry,
      {
        id: 4,
        name: "Dividends",
        categoryId: categories[5].id,
        category: categories[5],
        paid: true,
        date: "25/03/2023",
        amount: "350",
        type: "revenue",
      } as Entry,
      {
        id: 5,
        name: "Cooking gas",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "01/02/2023",
        amount: "70.80",
        type: "expense",
        description: "Description lorem ipsum",
      } as Entry,
      {
        id: 6,
        name: "Rent",
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: "05/02/2023",
        amount: "1500",
        type: "expense",
      } as Entry,
      {
        id: 7,
        name: "Salary",
        categoryId: categories[4].id,
        category: categories[4],
        paid: true,
        date: "15/02/2023",
        amount: "100",
        type: "revenue",
        description: "Description lorem ipsum",
      } as Entry,
      {
        id: 8,
        name: "Dividends",
        categoryId: categories[5].id,
        category: categories[5],
        paid: true,
        date: "25/02/2023",
        amount: "350",
        type: "revenue",
      } as Entry,
      {
        id: 9,
        name: "Electricity bill",
        categoryId: categories[0].id,
        category: categories[0],
        paid: true,
        date: "01/03/2023",
        amount: "70.80",
        type: "expense",
        description: "Description lorem ipsum",
      } as Entry,
      {
        id: 10,
        name: "Vitamins",
        categoryId: categories[1].id,
        category: categories[1],
        paid: true,
        date: "05/03/2023",
        amount: "15.20",
        type: "expense",
      } as Entry,
      {
        id: 11,
        name: "Salary",
        categoryId: categories[4].id,
        category: categories[4],
        paid: false,
        date: "15/03/2023",
        amount: "1300",
        type: "revenue",
        description: "Description lorem ipsum",
      } as Entry,
      {
        id: 12,
        name: "Dividends",
        categoryId: categories[5].id,
        category: categories[5],
        paid: false,
        date: "25/03/2023",
        amount: "100",
        type: "revenue",
      } as Entry,
    ];

    return { categories, entries };
  }
}
